// <auto-generated />
using LibraryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260219032646_UpdateLibraryModel6")]
    partial class UpdateLibraryModel6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("LibraryManagement.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BooksPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            BirthYear = 1990,
                            BooksPublished = 3,
                            FirstName = "Madeline",
                            LastName = "Miller"
                        },
                        new
                        {
                            AuthorId = 2,
                            BirthYear = 1990,
                            BooksPublished = 1,
                            FirstName = "Shelby",
                            LastName = "Van Pelt"
                        },
                        new
                        {
                            AuthorId = 3,
                            BirthYear = 1990,
                            BooksPublished = 66,
                            FirstName = "Margaret",
                            LastName = "Atwood"
                        },
                        new
                        {
                            AuthorId = 4,
                            BirthYear = 1990,
                            BooksPublished = 7,
                            FirstName = "Markus",
                            LastName = "Zusak"
                        },
                        new
                        {
                            AuthorId = 5,
                            BirthYear = 1990,
                            BooksPublished = 9,
                            FirstName = "Taylor Jenkins",
                            LastName = "Reid"
                        },
                        new
                        {
                            AuthorId = 6,
                            BirthYear = 1990,
                            BooksPublished = 34,
                            FirstName = "T.J.",
                            LastName = "Klune"
                        },
                        new
                        {
                            AuthorId = 7,
                            BirthYear = 1990,
                            BooksPublished = 3,
                            FirstName = "Gillian",
                            LastName = "Flynn"
                        },
                        new
                        {
                            AuthorId = 8,
                            BirthYear = 1990,
                            BooksPublished = 6,
                            FirstName = "R.F.",
                            LastName = "Kuang"
                        },
                        new
                        {
                            AuthorId = 9,
                            BirthYear = 1990,
                            BooksPublished = 30,
                            FirstName = "David",
                            LastName = "Levithan"
                        },
                        new
                        {
                            AuthorId = 10,
                            BirthYear = 1990,
                            BooksPublished = 7,
                            FirstName = "Antoine",
                            LastName = "de Saint-Exupery"
                        },
                        new
                        {
                            AuthorId = 11,
                            BirthYear = 1990,
                            BooksPublished = 2,
                            FirstName = "Stephen",
                            LastName = "Chbosky"
                        },
                        new
                        {
                            AuthorId = 12,
                            BirthYear = 1990,
                            BooksPublished = 40,
                            FirstName = "Lois",
                            LastName = "Lowry"
                        },
                        new
                        {
                            AuthorId = 13,
                            BirthYear = 1990,
                            BooksPublished = 3,
                            FirstName = "Alex",
                            LastName = "Michaelides"
                        },
                        new
                        {
                            AuthorId = 14,
                            BirthYear = 1990,
                            BooksPublished = 3,
                            FirstName = "Morgan",
                            LastName = "Housel"
                        },
                        new
                        {
                            AuthorId = 15,
                            BirthYear = 1990,
                            BooksPublished = 4,
                            FirstName = "Khaled",
                            LastName = "Hosseini"
                        },
                        new
                        {
                            AuthorId = 16,
                            BirthYear = 1990,
                            BooksPublished = 1,
                            FirstName = "Kathryn",
                            LastName = "Stockett"
                        },
                        new
                        {
                            AuthorId = 17,
                            BirthYear = 1990,
                            BooksPublished = 3,
                            FirstName = "Jason",
                            LastName = "Rekulak"
                        },
                        new
                        {
                            AuthorId = 18,
                            BirthYear = 1990,
                            BooksPublished = 26,
                            FirstName = "Rebecca",
                            LastName = "Yarros"
                        },
                        new
                        {
                            AuthorId = 19,
                            BirthYear = 1990,
                            BooksPublished = 80,
                            FirstName = "Agatha",
                            LastName = "Christie"
                        },
                        new
                        {
                            AuthorId = 20,
                            BirthYear = 1990,
                            BooksPublished = 26,
                            FirstName = "Colleen",
                            LastName = "Hoover"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AuthorId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LibraryBranchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("AuthorId1")
                        .IsUnique();

                    b.HasIndex("LibraryBranchId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 4,
                            ISBN = "978-1784162122",
                            LibraryBranchId = 1,
                            PublicationYear = 2005,
                            Title = "The Book Thief"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 5,
                            ISBN = "978-1501161933",
                            LibraryBranchId = 1,
                            PublicationYear = 2017,
                            Title = "The Seven Husbands of Evelyn Hugo"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 6,
                            ISBN = "978-1250217318",
                            LibraryBranchId = 1,
                            PublicationYear = 2020,
                            Title = "The House in the Cerulean Sea"
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 7,
                            ISBN = "978-3596188789",
                            LibraryBranchId = 1,
                            PublicationYear = 2012,
                            Title = "Gone Girl"
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 8,
                            ISBN = "978-0008501853",
                            LibraryBranchId = 1,
                            PublicationYear = 2022,
                            Title = "Babel"
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 1,
                            ISBN = "978-1408890042",
                            LibraryBranchId = 1,
                            PublicationYear = 2018,
                            Title = "Circe"
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 2,
                            ISBN = "978-0063254480",
                            LibraryBranchId = 1,
                            PublicationYear = 2022,
                            Title = "Remarkably Bright Creatures"
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 3,
                            ISBN = "978-0771008795",
                            LibraryBranchId = 1,
                            PublicationYear = 1985,
                            Title = "The Handmaid's Tale"
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 9,
                            ISBN = "978-0307931894",
                            LibraryBranchId = 1,
                            PublicationYear = 2012,
                            Title = "Every Day"
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 10,
                            ISBN = "978-3140464079",
                            LibraryBranchId = 1,
                            PublicationYear = 1943,
                            Title = "The Little Prince"
                        },
                        new
                        {
                            BookId = 11,
                            AuthorId = 11,
                            ISBN = "978-1847394071",
                            LibraryBranchId = 1,
                            PublicationYear = 1999,
                            Title = "The Perks of Being a Wallflower"
                        },
                        new
                        {
                            BookId = 12,
                            AuthorId = 12,
                            ISBN = "978-0440237686",
                            LibraryBranchId = 1,
                            PublicationYear = 1993,
                            Title = "The Giver"
                        },
                        new
                        {
                            BookId = 13,
                            AuthorId = 13,
                            ISBN = "978-1250301703",
                            LibraryBranchId = 1,
                            PublicationYear = 2019,
                            Title = "The Silent Patient"
                        },
                        new
                        {
                            BookId = 14,
                            AuthorId = 14,
                            ISBN = "978-0857197689",
                            LibraryBranchId = 1,
                            PublicationYear = 2020,
                            Title = "The Psychology of Money"
                        },
                        new
                        {
                            BookId = 15,
                            AuthorId = 15,
                            ISBN = "978-0670064915",
                            LibraryBranchId = 1,
                            PublicationYear = 2007,
                            Title = "A Thousand Splendid Suns"
                        },
                        new
                        {
                            BookId = 16,
                            AuthorId = 16,
                            ISBN = "978-0399155345",
                            LibraryBranchId = 1,
                            PublicationYear = 2009,
                            Title = "The Help"
                        },
                        new
                        {
                            BookId = 17,
                            AuthorId = 17,
                            ISBN = "978-1250819345",
                            LibraryBranchId = 1,
                            PublicationYear = 2022,
                            Title = "Hidden Pictures"
                        },
                        new
                        {
                            BookId = 18,
                            AuthorId = 18,
                            ISBN = "978-1649377579",
                            LibraryBranchId = 1,
                            PublicationYear = 2023,
                            Title = "Iron Flame"
                        },
                        new
                        {
                            BookId = 19,
                            AuthorId = 19,
                            ISBN = "978-0008123208",
                            LibraryBranchId = 1,
                            PublicationYear = 1939,
                            Title = "And Then There Were None"
                        },
                        new
                        {
                            BookId = 20,
                            AuthorId = 20,
                            ISBN = "978-1538724736",
                            LibraryBranchId = 2,
                            PublicationYear = 2018,
                            Title = "Verity"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcctOpenDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            AcctOpenDate = "Jan 22, 2025",
                            CustomerEmail = "maria.w@email.com",
                            CustomerFirstName = "Maria",
                            CustomerLastName = "Wang",
                            CustomerPhone = "236-356-7381"
                        },
                        new
                        {
                            CustomerId = 2,
                            AcctOpenDate = "Feb 14, 2025",
                            CustomerEmail = "emma.li@email.com",
                            CustomerFirstName = "Emma",
                            CustomerLastName = "Li",
                            CustomerPhone = "604-274-9981"
                        },
                        new
                        {
                            CustomerId = 3,
                            AcctOpenDate = "Feb 25, 2025",
                            CustomerEmail = "fatima.zhang@email.com",
                            CustomerFirstName = "Fatima",
                            CustomerLastName = "Zhang",
                            CustomerPhone = "234-100-4567"
                        },
                        new
                        {
                            CustomerId = 4,
                            AcctOpenDate = "Apr 28, 2025",
                            CustomerEmail = "anna.nguyen@email.com",
                            CustomerFirstName = "Anna",
                            CustomerLastName = "Nguyen",
                            CustomerPhone = "604-123-6607"
                        },
                        new
                        {
                            CustomerId = 5,
                            AcctOpenDate = "May 4, 2025",
                            CustomerEmail = "liv.garcia@email.com",
                            CustomerFirstName = "Olivia",
                            CustomerLastName = "Garcia",
                            CustomerPhone = "889-678-2231"
                        },
                        new
                        {
                            CustomerId = 6,
                            AcctOpenDate = "Jun 3, 2025",
                            CustomerEmail = "sarah.kumar@email.com",
                            CustomerFirstName = "Sarah",
                            CustomerLastName = "Kumar",
                            CustomerPhone = "604-265-5689"
                        },
                        new
                        {
                            CustomerId = 7,
                            AcctOpenDate = "Jun 7, 2025",
                            CustomerEmail = "mary.ali@email.com",
                            CustomerFirstName = "Mary",
                            CustomerLastName = "Ali",
                            CustomerPhone = "604-654-7819"
                        },
                        new
                        {
                            CustomerId = 8,
                            AcctOpenDate = "Jul 2, 2025",
                            CustomerEmail = "sofia.smith@email.com",
                            CustomerFirstName = "Sofia",
                            CustomerLastName = "Smith",
                            CustomerPhone = "235-246-0921"
                        },
                        new
                        {
                            CustomerId = 9,
                            AcctOpenDate = "Jul 9, 2025",
                            CustomerEmail = "lizzie.johnson@email.com",
                            CustomerFirstName = "Elizabeth",
                            CustomerLastName = "Johnson",
                            CustomerPhone = "604-120-2345"
                        },
                        new
                        {
                            CustomerId = 10,
                            AcctOpenDate = "Jul 12, 2025",
                            CustomerEmail = "issa.williams@email.com",
                            CustomerFirstName = "Isabella",
                            CustomerLastName = "Williams",
                            CustomerPhone = "778-099-9876"
                        },
                        new
                        {
                            CustomerId = 11,
                            AcctOpenDate = "Jul 19, 2025",
                            CustomerEmail = "muhammad.brown@email.com",
                            CustomerFirstName = "Muhammad",
                            CustomerLastName = "Brown",
                            CustomerPhone = "604-180-1234"
                        },
                        new
                        {
                            CustomerId = 12,
                            AcctOpenDate = "Jul 22, 2025",
                            CustomerEmail = "john.jones@email.com",
                            CustomerFirstName = "John",
                            CustomerLastName = "Jones",
                            CustomerPhone = "604-457-0200"
                        },
                        new
                        {
                            CustomerId = 13,
                            AcctOpenDate = "Aug 10, 2025",
                            CustomerEmail = "james.miller@email.com",
                            CustomerFirstName = "James",
                            CustomerLastName = "Miller",
                            CustomerPhone = "604-123-2012"
                        },
                        new
                        {
                            CustomerId = 14,
                            AcctOpenDate = "Aug 13, 2025",
                            CustomerEmail = "david.davis@email.com",
                            CustomerFirstName = "David",
                            CustomerLastName = "Davis",
                            CustomerPhone = "912-942-8671"
                        },
                        new
                        {
                            CustomerId = 15,
                            AcctOpenDate = "Oct 25, 2025",
                            CustomerEmail = "ahmed.rodriguez@email.com",
                            CustomerFirstName = "Ahmed",
                            CustomerLastName = "Rodriguez",
                            CustomerPhone = "604-227-4252"
                        },
                        new
                        {
                            CustomerId = 16,
                            AcctOpenDate = "Nov 6, 2025",
                            CustomerEmail = "mike.martinez@email.com",
                            CustomerFirstName = "Michael",
                            CustomerLastName = "Martinez",
                            CustomerPhone = "224-764-7781"
                        },
                        new
                        {
                            CustomerId = 17,
                            AcctOpenDate = "Nov 25, 2025",
                            CustomerEmail = "ali.hern@email.com",
                            CustomerFirstName = "Ali",
                            CustomerLastName = "Hernandez",
                            CustomerPhone = "604-246-3453"
                        },
                        new
                        {
                            CustomerId = 18,
                            AcctOpenDate = "Dec 1, 2025",
                            CustomerEmail = "omar.gonzi@email.com",
                            CustomerFirstName = "Omar",
                            CustomerLastName = "Gonzalez",
                            CustomerPhone = "887-063-2342"
                        },
                        new
                        {
                            CustomerId = 19,
                            AcctOpenDate = "Dec 28, 2025",
                            CustomerEmail = "joe.mueller@email.com",
                            CustomerFirstName = "Joseph",
                            CustomerLastName = "Mueller",
                            CustomerPhone = "604-567-8555"
                        },
                        new
                        {
                            CustomerId = 20,
                            AcctOpenDate = "Jan 4, 2026",
                            CustomerEmail = "santiago.s@email.com",
                            CustomerFirstName = "Santiago",
                            CustomerLastName = "Silva",
                            CustomerPhone = "654-890-7843"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.LibraryBranch", b =>
                {
                    b.Property<int>("LibraryBranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LibraryBranchId");

                    b.ToTable("LibraryBranches");

                    b.HasData(
                        new
                        {
                            LibraryBranchId = 1,
                            BranchAddress = "123 Library St, Vancouver",
                            BranchName = "Main Branch"
                        },
                        new
                        {
                            LibraryBranchId = 2,
                            BranchAddress = "456 City Ave, Vancouver",
                            BranchName = "Downtown Branch"
                        },
                        new
                        {
                            LibraryBranchId = 3,
                            BranchAddress = "789 Main Ave, Vancouver",
                            BranchName = "Lower Mainland Branch"
                        },
                        new
                        {
                            LibraryBranchId = 4,
                            BranchAddress = "1107 First St, Vancouver",
                            BranchName = "University Branch"
                        },
                        new
                        {
                            LibraryBranchId = 5,
                            BranchAddress = "13755 102 Ave, Vancouver",
                            BranchName = "Civic Branch"
                        },
                        new
                        {
                            LibraryBranchId = 6,
                            BranchAddress = "231 31st St, Vancouver",
                            BranchName = "Provincial Branch"
                        },
                        new
                        {
                            LibraryBranchId = 7,
                            BranchAddress = "1007 Station Rd, Vancouver",
                            BranchName = "City Centre Branch"
                        },
                        new
                        {
                            LibraryBranchId = 8,
                            BranchAddress = "656 High St, Vancouver",
                            BranchName = "North Branch"
                        },
                        new
                        {
                            LibraryBranchId = 9,
                            BranchAddress = "7481 Park Ave, Vancouver",
                            BranchName = "Central Branch"
                        },
                        new
                        {
                            LibraryBranchId = 10,
                            BranchAddress = "331 View Rd, Vancouver",
                            BranchName = "South Branch"
                        },
                        new
                        {
                            LibraryBranchId = 11,
                            BranchAddress = "9970 Center Street, Vancouver",
                            BranchName = "East Branch"
                        },
                        new
                        {
                            LibraryBranchId = 12,
                            BranchAddress = "385 Queens Rd, Vancouver",
                            BranchName = "West Branch"
                        },
                        new
                        {
                            LibraryBranchId = 13,
                            BranchAddress = "17552 Green Lane, Vancouver",
                            BranchName = "Community Branch"
                        },
                        new
                        {
                            LibraryBranchId = 14,
                            BranchAddress = "108 School St, Vancouver",
                            BranchName = "Regional Branch"
                        },
                        new
                        {
                            LibraryBranchId = 15,
                            BranchAddress = "2219 Elm St, Vancouver",
                            BranchName = "University Branch"
                        },
                        new
                        {
                            LibraryBranchId = 16,
                            BranchAddress = "3441 Victoria Rd, Vancouver",
                            BranchName = "Ridge Branch"
                        },
                        new
                        {
                            LibraryBranchId = 17,
                            BranchAddress = "102 Hamilton Heights, Vancouver",
                            BranchName = "Valley Branch"
                        },
                        new
                        {
                            LibraryBranchId = 18,
                            BranchAddress = "389 Maple Ridge, Vancouver",
                            BranchName = "Rural Branch"
                        },
                        new
                        {
                            LibraryBranchId = 19,
                            BranchAddress = "6273 Sun Valley, Vancouver",
                            BranchName = "Uptown Branch"
                        },
                        new
                        {
                            LibraryBranchId = 20,
                            BranchAddress = "901 Campus Rd, Vancouver",
                            BranchName = "First Branch"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.Book", b =>
                {
                    b.HasOne("LibraryManagement.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.Author", null)
                        .WithOne("Book")
                        .HasForeignKey("LibraryManagement.Models.Book", "AuthorId1");

                    b.HasOne("LibraryManagement.Models.LibraryBranch", "LibraryBranch")
                        .WithMany()
                        .HasForeignKey("LibraryBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("LibraryBranch");
                });

            modelBuilder.Entity("LibraryManagement.Models.Author", b =>
                {
                    b.Navigation("Book")
                        .IsRequired();

                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
