// <auto-generated />
using LibraryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260216050334_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BooksPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            BooksPublished = 3,
                            FirstName = "Madeline",
                            LastName = "Miller"
                        },
                        new
                        {
                            AuthorId = 2,
                            BooksPublished = 1,
                            FirstName = "Shelby",
                            LastName = "Van Pelt"
                        },
                        new
                        {
                            AuthorId = 3,
                            BooksPublished = 66,
                            FirstName = "Margaret",
                            LastName = "Atwood"
                        },
                        new
                        {
                            AuthorId = 20,
                            BooksPublished = 80,
                            FirstName = "Agatha",
                            LastName = "Christie"
                        });
                });

            modelBuilder.Entity("Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LibraryBranchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LibraryBranchId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            ISBN = "978-0747532699",
                            LibraryBranchId = 1,
                            PublicationYear = 1997,
                            Title = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2,
                            ISBN = "978-0547928227",
                            LibraryBranchId = 1,
                            PublicationYear = 1937,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            BookId = 20,
                            AuthorId = 20,
                            ISBN = "978-0062073488",
                            LibraryBranchId = 2,
                            PublicationYear = 1939,
                            Title = "And Then There Were None"
                        });
                });

            modelBuilder.Entity("Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcctOpenDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            AcctOpenDate = "Feb 1, 2025",
                            CustomerEmail = "john.smith@email.com",
                            CustomerFirstName = "John",
                            CustomerLastName = "Smith",
                            CustomerPhone = "604-123-4567"
                        },
                        new
                        {
                            CustomerId = 20,
                            AcctOpenDate = "Feb 1, 2025",
                            CustomerEmail = "sarah.w@email.com",
                            CustomerFirstName = "Sarah",
                            CustomerLastName = "Wilson",
                            CustomerPhone = "604-987-6543"
                        });
                });

            modelBuilder.Entity("LibraryBranch", b =>
                {
                    b.Property<int>("LibraryBranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LibraryBranchId");

                    b.ToTable("LibraryBranches");

                    b.HasData(
                        new
                        {
                            LibraryBranchId = 1,
                            BranchAddress = "123 Library St, Vancouver",
                            BranchName = "Main Branch"
                        },
                        new
                        {
                            LibraryBranchId = 2,
                            BranchAddress = "456 City Ave, Vancouver",
                            BranchName = "Downtown Branch"
                        },
                        new
                        {
                            LibraryBranchId = 5,
                            BranchAddress = "789 Campus Rd, Vancouver",
                            BranchName = "University Branch"
                        });
                });

            modelBuilder.Entity("Book", b =>
                {
                    b.HasOne("Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryBranch", "LibraryBranch")
                        .WithMany()
                        .HasForeignKey("LibraryBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("LibraryBranch");
                });
#pragma warning restore 612, 618
        }
    }
}
